import { Recipe, Project } from '../types';

export const PRESET_RECIPES: Recipe[] = [
  {
    id: 'recipe-ai-ugc',
    name: 'AI UGC — Character Image → Multi-Shot Talking Video',
    description: 'Anchor character photo transformed into sequential spoken 5s video shots via Gemini Omni / Fal.ai with independent shot regeneration.',
    isCustom: false,
    iconName: 'UserCheck',
    estimatedDuration: '25-30s',
    inputRequirements: ['Character Reference Image', 'Script Outline', 'Platform & Language', 'Product focus (optional)'],
    steps: [
      {
        stepNumber: 1,
        name: 'Divide Script into 5s Shot Breakdown',
        description: 'AI Creative Agent parses hook, problem, solution, and CTA into discrete 4-6s scenes.',
        provider: 'Gemini Script AI',
        defaultDurationSec: 5,
        promptTemplate: 'Break script into 5 sequential shots with dialogue and camera actions.',
      },
      {
        stepNumber: 2,
        name: 'Character Reference Anchor Injection',
        description: 'Bind digital character traits and reference photo to ensure face consistency across all shots.',
        provider: 'Gemini Omni / Fal.ai',
        promptTemplate: 'Apply anchor reference image of character with high facial fidelity.',
      },
      {
        stepNumber: 3,
        name: 'Generate Individual Shots (~5s each)',
        description: 'Generate each video shot with lip-sync dialogue and natural facial expressions.',
        provider: 'Gemini Omni / Fal.ai',
        defaultDurationSec: 5,
        promptTemplate: 'Generate shot #{shotNumber}: {spokenText} with {cameraMovement}.',
      },
      {
        stepNumber: 4,
        name: 'Shot Review & Individual Regeneration',
        description: 'Preview shots in isolation. Regenerate any imperfect shot without re-rendering the whole video.',
        provider: 'Gemini Omni / Fal.ai',
        promptTemplate: 'Regenerate shot #{shotNumber} with adjusted direction.',
      },
      {
        stepNumber: 5,
        name: 'Rebuild Creative & Audio Stitching',
        description: 'Assemble all validated shots into final composite video with captions and pacing.',
        provider: 'Vite Compositor',
        promptTemplate: 'Stitch shots 1..N into unified final MP4 creative.',
      },
    ],
  },
  {
    id: 'recipe-product-ugc',
    name: 'Product UGC (Character + Hero Feature Demo)',
    description: 'Digital creator holding, trying, or talking through a specific product problem and showing immediate results.',
    isCustom: false,
    iconName: 'Package',
    estimatedDuration: '20-25s',
    inputRequirements: ['Character Image', 'Product USP & Hero Hook', 'Target Pain Point'],
    steps: [
      {
        stepNumber: 1,
        name: 'Hook with Problem + Product In Hand',
        description: 'First 3 seconds visually introduces the solution in creator hands.',
        provider: 'Gemini Omni / Fal.ai',
        defaultDurationSec: 5,
        promptTemplate: 'Character holding product, speaking hook to camera.',
      },
      {
        stepNumber: 2,
        name: 'Demonstration & Personal Experience',
        description: 'Creator describes the transformation and why alternatives failed.',
        provider: 'Gemini Omni / Fal.ai',
        defaultDurationSec: 6,
        promptTemplate: 'Creator demonstrating product usage naturally.',
      },
      {
        stepNumber: 3,
        name: 'Clear Call to Action & Offer',
        description: 'Direct closing urging user to visit link or claim initial trial.',
        provider: 'Gemini Omni / Fal.ai',
        defaultDurationSec: 5,
        promptTemplate: 'Closing CTA with promotional banner overlay.',
      },
    ],
  },
  {
    id: 'recipe-faceless',
    name: 'Faceless UGC (B-roll + Voiceover + Dynamic Subtitles)',
    description: 'High-pacing aesthetic video clips synchronized with punchy voice-over dialogue and word-by-word highlighted captions.',
    isCustom: false,
    iconName: 'Video',
    estimatedDuration: '15-30s',
    inputRequirements: ['Topic / Myth to Bust', 'Visual Aesthetic Style', 'Target Channel'],
    steps: [
      {
        stepNumber: 1,
        name: 'Punchy Voice-over Generation',
        description: 'Generate lifelike narrator audio with conversational cadence.',
        provider: 'Gemini TTS',
        promptTemplate: 'Generate dynamic audio voiceover with emphatic pauses.',
      },
      {
        stepNumber: 2,
        name: 'Aesthetic B-Roll Shot Sequence',
        description: 'Generate 4-5 high-contrast background video shots matching the topic.',
        provider: 'Fal.ai Wan/Kling',
        promptTemplate: 'Cinematic atmospheric macro footage related to theme.',
      },
      {
        stepNumber: 3,
        name: 'Karaoke Style Subtitle Timing',
        description: 'Synchronize word-level highlighted typography.',
        provider: 'Vite Compositor',
        promptTemplate: 'Render high-retention center captions.',
      },
    ],
  },
  {
    id: 'recipe-cinematic',
    name: 'Cinematic Brand Reel (Image → Video Sequence)',
    description: 'Transform high-concept product renders or editorial stills into slow-motion, dynamic camera motion clips.',
    isCustom: false,
    iconName: 'Film',
    estimatedDuration: '15-20s',
    inputRequirements: ['Product / Brand Still Renders', 'Desired Camera Motion (Orbit, Dolly, Crane)'],
    steps: [
      {
        stepNumber: 1,
        name: 'Image Enhancement & Camera Path Prompting',
        description: 'Define lighting, depth of field, and camera physics.',
        provider: 'Fal.ai Wan/Kling',
        promptTemplate: 'Animate still image with smooth 60fps orbital camera sweep.',
      },
      {
        stepNumber: 2,
        name: 'Atmospheric Sound Design & Grade',
        description: 'Pair with subtle ambient audio and brand color toning.',
        provider: 'Vite Compositor',
        promptTemplate: 'Assemble luxury brand grade sequence.',
      },
    ],
  },
  {
    id: 'recipe-carousel',
    name: 'Instagram Educational Carousel (Slide Framework)',
    description: '7-10 slide swipeable value breakdown: Hook Slide → Context → 3 Actionable Insights → Summary → Save CTA.',
    isCustom: false,
    iconName: 'Layers',
    estimatedDuration: 'Static Slides',
    inputRequirements: ['Content Pillar Topic', '3 Key Takeaways', 'Brand Font & Color Palette'],
    steps: [
      {
        stepNumber: 1,
        name: 'Slide 1: Scroll-Stopping Title & Cover',
        description: 'Bold controversial question or counter-intuitive statement.',
        provider: 'Gemini Script AI',
        promptTemplate: 'Craft slide 1 high-CTR cover copy and visual layout.',
      },
      {
        stepNumber: 2,
        name: 'Slides 2-6: Bite-sized Value Nuggets',
        description: 'Concise bullet points with clear visual hierarchy.',
        provider: 'Gemini Script AI',
        promptTemplate: 'Structure 4 body slides with maximum scannability.',
      },
      {
        stepNumber: 3,
        name: 'Slide 7: Save & Share Call-to-Action',
        description: 'Prompts viewer to bookmark for later reference.',
        provider: 'Gemini Script AI',
        promptTemplate: 'Write high-save CTA slide.',
      },
    ],
  },
];

export const SAMPLE_NOOTRION_PROJECT: Project = {
  id: 'proj-nootrion-default',
  name: 'Nootrion',
  description: 'Performance cerebral, foco e clareza mental através de suplementação nootrópica avançada.',
  codePrefix: 'NOO',
  createdAt: '2026-08-15T10:00:00Z',
  updatedAt: '2026-08-20T10:00:00Z',
  brandMemory: {
    name: 'Nootrion',
    description: 'Nootrion é uma marca de suplementos orientados para a máxima performance cerebral, foco sustentado e clareza cognitiva sem picos ou quebras de energia.',
    businessArea: 'Saúde Cognitiva, Suplementação & Biohacking',
    targetAudience: {
      demographics: 'Profissionais de alta performance, empreendedores, programadores, estudantes e criadores de conteúdo (24–45 anos).',
      painPoints: [
        'Cansaço mental no meio da tarde e dificuldade de concentração prolongada.',
        'Dependência de excesso de café que gera ansiedade, tremores e quebras bruscas.',
        'Brain fog (névoa mental) e sobrecarga de estímulos diários.',
        'Falta de clareza para tomadas de decisão importantes.',
      ],
      desires: [
        'Foco fluido e estado de flow sustentado durante 6 a 8 horas.',
        'Energia mental limpa, calma e sem taquicardia.',
        'Memória de trabalho afiada e velocidade de raciocínio.',
      ],
    },
    positioning: 'O suplemento de inteligência e foco limpo para quem constrói e cria sob alta demanda.',
    communicationTone: {
      tone: 'Direto, científico porém acessível, empático, sofisticado e confiante.',
      styleGuide: 'Evitar promessas milagrosas baratas; focar em mecanismos biológicos reais (L-Teanina, Bacopa, Citicolina) de forma descomplicada.',
      dos: [
        'Explicar o "porquê" por trás da cafeína combinada com nootrópicos.',
        'Usar ganchos que tocam na rotina real de trabalho e fadiga mental.',
        'Manter tom conversacional em estilo UGC autêntico.',
      ],
      donts: [
        'Não usar jargões de "cura mágica" ou promessas irreais de QI.',
        'Não falar mal genericamente de café sem explicar o papel dos adaptógenos.',
      ],
    },
    language: 'Português (PT / BR)',
    channels: ['Instagram', 'TikTok', 'YouTube', 'Paid Ads'],
    visualIdentity: {
      primaryColor: '#0F172A',
      accentColor: '#10B981',
      fontTitle: 'Plus Jakarta Sans',
      fontBody: 'Inter',
      logoUrl: '',
      styleAesthetic: 'Clean minimalista dark com toques de verde bio-óptico e fotografia autêntica.',
    },
    products: [
      {
        id: 'prod-noo-flow',
        name: 'Nootrion Flow State',
        type: 'Product',
        description: 'Fórmula diária para foco prolongado, memória e clareza mental sem ansiedade.',
        usp: 'Combinação patenteada de L-Teanina, Bacopa Monnieri, Citicolina e Cafeína Natural.',
        pricing: '49.90€ / frasco mensal',
        heroHook: 'Bebes 3 cafés e continuas com sono às 15h? O problema não é falta de cafeína.',
      },
      {
        id: 'prod-noo-sleep',
        name: 'Nootrion Deep Recovery',
        type: 'Product',
        description: 'Regeneração cerebral noturna e sono REM profundo para acordar 100% lúcido.',
        usp: 'Bisglicinato de Magnésio, Apigenina e L-Glicina.',
        pricing: '44.90€ / frasco',
        heroHook: 'Se o teu cérebro não descansa à noite, o teu foco amanhã já começa a 50%.',
      },
    ],
    differentiation: 'Fórmulas com dosagens transparentes e clinicamente comprovadas, sem misturas proprietárias ocultas.',
    otherNotes: 'A marca valoriza a ciência do cérebro, hábitos de trabalho profundo e biohacking diário.',
  },
  creativeMemory: [
    {
      id: 'mem-1',
      date: '2026-08-10',
      type: 'hook',
      content: 'Bebes café e continuas cansado? O problema não é a cafeína, é como o teu cérebro processa adenosina.',
      topic: 'Cafeína & Fadiga mental',
      channel: 'Instagram',
      format: 'AI UGC',
      characterName: 'Sofia',
      performanceSummary: 'Vencedor: Retenção de 68% nos primeiros 3 segundos.',
      isWinner: true,
    },
    {
      id: 'mem-2',
      date: '2026-08-12',
      type: 'hook',
      content: 'O erro que 90% dos profissionais cometem às 14h quando sentem quebra de energia.',
      topic: 'Quebra da tarde',
      channel: 'TikTok',
      format: 'AI UGC',
      characterName: 'Sofia',
      performanceSummary: 'CTR 4.8%, elevado volume de partilhas.',
      isWinner: true,
    },
    {
      id: 'mem-3',
      date: '2026-08-05',
      type: 'failed',
      content: 'Descobre o suplemento número 1 do mundo para o cérebro.',
      topic: 'Genérico',
      channel: 'Paid Ads',
      format: 'Product Video',
      performanceSummary: 'Falhou: Gancho soou a anúncio genérico, CTR < 0.9%.',
      isWinner: false,
    },
  ],
  characters: [
    {
      id: 'char-sofia',
      name: 'Sofia',
      role: 'Criadora de Conteúdo & Entusiasta de Produtividade',
      ageGroup: '27 anos',
      personality: 'Curiosa, conversacional, autêntica, direta e expressiva.',
      speakingStyle: 'Ritmo dinâmico, olhar focado na câmara, tom amigável de recomendação genuína.',
      visualTraits: 'Mulher jovem com cabelo castanho ondulado, vestuário casual clean, iluminação natural de secretária/escritório.',
      referenceImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
      shotCount: 14,
      createdAt: '2026-08-16T12:00:00Z',
    },
    {
      id: 'char-marcus',
      name: 'Marcus',
      role: 'Biohacker & Software Engineer',
      ageGroup: '32 anos',
      personality: 'Analítico, calmo, focado em dados e rotinas de alta performance.',
      speakingStyle: 'Tom seguro, pausado, enfatiza termos científicos de forma simples.',
      visualTraits: 'Homem jovem com barba cuidada, óculos minimalistas, t-shirt preta neutra, setup com monitores desfocados ao fundo.',
      referenceImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
      shotCount: 8,
      createdAt: '2026-08-17T15:00:00Z',
    },
  ],
  creatives: [
    {
      id: 'cr-noo-00127',
      code: '#NOO-00127',
      title: 'Bebes café e continuas cansado? (Mecanismo Adenosina)',
      theme: 'Fadiga Mental & Concentração',
      topic: 'Cafeína vs Nootrópicos',
      channel: 'Instagram',
      contentType: 'Reel',
      creativeFormat: 'AI UGC',
      creativeObjective: 'direct_sale_cta',
      recipeId: 'recipe-ai-ugc',
      characterId: 'char-sofia',
      status: 'WINNER',
      hook: 'Bebes café e continuas cansado? Eu também achava que precisava de mais uma chávena...',
      scriptBody: 'Sofia explica a razão pela qual a cafeína sozinha mascara a fadiga sem reabastecer a acetilcolina cerebral, apresentando Nootrion Flow.',
      cta: 'Clica no link da bio para testar Nootrion com 30 dias de garantia de foco.',
      targetDuration: 25,
      previewImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
      tags: ['UGC', 'Cafeína', 'Sofia', 'Foco', 'Vencedor'],
      shots: [
        {
          id: 'shot-1',
          shotNumber: 1,
          type: 'Hook',
          durationSec: 5,
          spokenText: 'Bebes café e continuas cansado?',
          visualPrompt: 'Sofia olhando diretamente para a câmara do telemóvel com expressão intrigada e empática, segurando uma caneca de café.',
          cameraMovement: 'Subtil zoom in com corte rápido.',
          characterEmotion: 'Intrigada & curiosa',
          onScreenText: 'Bebes café e continuas cansado? ☕❌',
          imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
        {
          id: 'shot-2',
          shotNumber: 2,
          type: 'Problem',
          durationSec: 5,
          spokenText: 'Eu também achava que precisava simplesmente de beber mais uma chávena...',
          visualPrompt: 'Sofia gesticulando naturalmente com a mão livre, sentada à secretária com computador portátil.',
          cameraMovement: 'Câmara estática na altura dos olhos.',
          characterEmotion: 'Relatável e sincera',
          onScreenText: '"Só mais um café não resolve..."',
          imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
        {
          id: 'shot-3',
          shotNumber: 3,
          type: 'Development',
          durationSec: 5,
          spokenText: 'Mas percebi que o problema não era falta de energia, era falta de neurotransmissores de foco.',
          visualPrompt: 'Sofia a apontar suavemente para a têmpora com ar de revelação.',
          cameraMovement: 'Plano médio com iluminação quente.',
          characterEmotion: 'Reveladora & didática',
          onScreenText: 'O segredo: Neurotransmissores 🧠',
          imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
        {
          id: 'shot-4',
          shotNumber: 4,
          type: 'Solution',
          durationSec: 5,
          spokenText: 'Foi quando comecei a tomar Nootrion Flow State antes das sessões de trabalho profundo.',
          visualPrompt: 'Sofia a segurar o frasco elegante de Nootrion Flow State com um sorriso confiante.',
          cameraMovement: 'Ligeiro movimento de mão segurando o produto.',
          characterEmotion: 'Satisfeita & confiante',
          onScreenText: 'Nootrion Flow State 🌿⚡',
          imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
        {
          id: 'shot-5',
          shotNumber: 5,
          type: 'CTA',
          durationSec: 5,
          spokenText: 'Se queres 6 horas de foco limpo sem tremores, clica no link abaixo.',
          visualPrompt: 'Sofia a apontar para a parte inferior do ecrã com sorriso acolhedor.',
          cameraMovement: 'Close-up final com CTA gráfico.',
          characterEmotion: 'Convidativa',
          onScreenText: '🔗 Clica no link e testa com 30 dias de garantia!',
          imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
      ],
      performance: {
        views: 142800,
        likes: 9340,
        comments: 482,
        shares: 1820,
        saves: 4120,
        retentionRatePct: 62.4,
        ctrPct: 4.85,
        conversions: 386,
        roas: 4.2,
        recordedAt: '2026-08-18',
        notes: 'Melhor criativo do mês de Agosto. O gancho com café gerou 4x mais partilhas que o habitual.',
      },
      createdAt: '2026-08-16T14:00:00Z',
      updatedAt: '2026-08-18T18:00:00Z',
      notes: 'Criativo validado como Top Winner.',
    },
    {
      id: 'cr-noo-00128',
      code: '#NOO-00128',
      title: 'O protocolo dos programadores para evitar Brain Fog',
      theme: 'Produtividade & Trabalho Profundo',
      topic: 'Rotina de Deep Work',
      channel: 'TikTok',
      contentType: 'TikTok Video',
      creativeFormat: 'AI UGC',
      creativeObjective: 'indirect_lead_dm',
      recipeId: 'recipe-ai-ugc',
      characterId: 'char-marcus',
      status: 'PUBLISHED',
      hook: 'Se passas 8 horas ao computador e chegas às 16h sem conseguir pensar em nada...',
      scriptBody: 'Marcus demonstra a sua rotina de 3 passos para manter a clareza analítica em dias de muito código. Envia DM com a palavra PROTOCOLO para receber o breakdown.',
      cta: 'Envia-me "PROTOCOLO" na DM para eu te mandar a rotina completa em PDF.',
      targetDuration: 24,
      previewImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
      tags: ['Marcus', 'Tech', 'TikTok', 'Deep Work', 'Lead DM'],
      shots: [
        {
          id: 'shot-m-1',
          shotNumber: 1,
          type: 'Hook',
          durationSec: 5,
          spokenText: 'Se chegas às 16h em frente ao ecrã sem conseguir raciocinar...',
          visualPrompt: 'Marcus a olhar para a câmara do telemóvel à secretária.',
          cameraMovement: 'Corte dinâmico.',
          characterEmotion: 'Empático e direto',
          imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
      ],
      performance: {
        views: 89400,
        likes: 5410,
        comments: 290,
        shares: 980,
        saves: 2310,
        retentionRatePct: 54.1,
        ctrPct: 3.9,
        conversions: 194,
        roas: 3.4,
        recordedAt: '2026-08-19',
      },
      createdAt: '2026-08-17T11:00:00Z',
      updatedAt: '2026-08-19T16:00:00Z',
    },
    {
      id: 'cr-noo-00129',
      code: '#NOO-00129',
      title: '3 Hábitos que destroem a tua memória de trabalho',
      theme: 'Neurociência & Hábitos',
      topic: 'Educação Cognitiva',
      channel: 'Instagram',
      contentType: 'Carousel',
      creativeFormat: 'Carousel',
      creativeObjective: 'authority_educational',
      recipeId: 'recipe-carousel',
      status: 'APPROVED',
      hook: 'Estes 3 hábitos diários estão a drenar 40% da tua capacidade de foco.',
      scriptBody: 'Carrossel de 7 slides detalhando multitasking, excesso de cafeína pós-15h e falta de magnésio bioativo.',
      cta: 'Guarda este post para rever na próxima segunda-feira e partilha.',
      targetDuration: 0,
      previewImageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600&auto=format&fit=crop&q=80',
      tags: ['Carrossel', 'Educativo', 'Memória', 'Autoridade'],
      shots: [],
      createdAt: '2026-08-18T09:00:00Z',
      updatedAt: '2026-08-18T10:00:00Z',
    },
    {
      id: 'cr-noo-00130',
      code: '#NOO-00130',
      title: 'Por que o teu sono está a sabotar a tua inteligência amanhã',
      theme: 'Sono & Recuperação Cerebral',
      topic: 'Nootrion Deep Recovery',
      channel: 'Instagram',
      contentType: 'Reel',
      creativeFormat: 'AI UGC',
      creativeObjective: 'direct_sale_cta',
      recipeId: 'recipe-ai-ugc',
      characterId: 'char-sofia',
      status: 'PRODUCTION',
      hook: 'Se dormes 8 horas e acordas como se um camião te tivesse passado por cima...',
      scriptBody: 'Explicação sobre a fase REM do sono e como a apigenina + magnésio facilitam a limpeza glinfática.',
      cta: 'Clica para conhecer Nootrion Deep Recovery.',
      targetDuration: 25,
      previewImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
      tags: ['Sono', 'Sofia', 'Recovery', 'Produção'],
      shots: [
        {
          id: 'shot-s-1',
          shotNumber: 1,
          type: 'Hook',
          durationSec: 5,
          spokenText: 'Se dormes 8 horas e acordas como se um camião te tivesse passado por cima...',
          visualPrompt: 'Sofia sentada na cama com almofadas ao fundo, falando de forma acolhedora para o telemóvel.',
          cameraMovement: 'Plano médio vertical.',
          characterEmotion: 'Empática e sonolenta simulada',
          onScreenText: 'Dormes 8h e continuas cansado? 😴',
          imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
          status: 'ready',
        },
        {
          id: 'shot-s-2',
          shotNumber: 2,
          type: 'Problem',
          durationSec: 5,
          spokenText: 'A quantidade de horas não serve de nada se não atingires sono REM profundo.',
          visualPrompt: 'Sofia a explicar com gesto de equilíbrio.',
          cameraMovement: 'Zoom ligeiro.',
          characterEmotion: 'Explicativa',
          imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
          status: 'draft',
        },
      ],
      createdAt: '2026-08-19T14:00:00Z',
      updatedAt: '2026-08-20T08:00:00Z',
    },
  ],
  customRecipes: [],
  insights: [
    {
      id: 'ins-1',
      createdAt: '2026-08-19T12:00:00Z',
      summary: 'A personagem Sofia em vídeos UGC com ganchos baseados em perguntas sobre café gera 42% maior retenção e taxa de conversão 2.4x superior à média do canal.',
      winningPatterns: [
        {
          category: 'Hooks & Abertura',
          finding: 'Ganchos que contrastam hábito diário comum (café) com sintoma inesperado (cansaço às 14h) atingiram mais de 60% de retenção no segundo 3.',
          impact: '+42% Retenção no 3s',
          confidenceScore: 94,
        },
        {
          category: 'Personagem & UGC',
          finding: 'A personagem Sofia entrega mensagens científicas com tom 68% mais autêntico que voice-over anónimo.',
          impact: '2.4x Taxa de Conversão',
          confidenceScore: 91,
        },
        {
          category: 'Duração dos Shots',
          finding: 'Shots individuais com exatamente 4 a 5 segundos de corte mantêm a curva de retenção estável sem desistência.',
          impact: '+28% Watch Time Completo',
          confidenceScore: 89,
        },
      ],
      recommendations: [
        {
          title: 'Série: "O que acontece ao teu cérebro às 15h"',
          concept: 'Sofia a demonstrar a transição de cafeína para nootrópicos com corte a cada 4 segundos.',
          expectedImpact: 'Alto volume de partilhas e saves',
          suggestedFormat: 'AI UGC Reel',
        },
        {
          title: 'Comparativo Visual: Café vs Nootrion Flow',
          concept: 'Split shot lado a lado mostrando o pico/quebra de cafeína versus a curva contínua de foco.',
          expectedImpact: 'CTR de anúncio > 4.5%',
          suggestedFormat: 'AI UGC + B-Roll',
        },
      ],
    },
  ],
  aiConfig: {
    defaultModel: 'gemini-3.6-flash',
    falApiKey: '',
    openaiApiKey: '',
    preferredVideoEngine: 'gemini_omni',
    voiceEngine: 'gemini_tts',
    creditsAvailable: 2500,
    creditsUsed: 380,
  },
};
